//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace dataoke_api_QQ {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class dataoke_api {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal dataoke_api() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dataoke_api_QQ.dataoke_api", typeof(dataoke_api).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 http://uland.taobao.com/coupon/edetail?activityId={$activityId$}&amp;itemId={$itemId$}&amp;pid={$pid$}&amp;dx=1&amp;src=tkm_tl 的本地化字符串。
        /// </summary>
        internal static string quan_template {
            get {
                return ResourceManager.GetString("quan_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;zh-CN&quot;&gt;
        ///
        ///&lt;head&gt;
        ///
        ///	&lt;meta charset=&quot;utf-8&quot;&gt;
        ///	&lt;title&gt;{$title$}&lt;/title&gt;
        ///	&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;&gt;
        ///
        ///	&lt;meta name=&quot;robots&quot; content=&quot;index,follow&quot;&gt;
        ///	&lt;meta name=&quot;application-name&quot; content=&quot;bootcss.com&quot;&gt;
        ///	&lt;meta property=&quot;qc:admins&quot; content=&quot;1603466166416277433363757477167&quot; /&gt;
        ///
        ///	&lt;!-- Site CSS --&gt;
        ///	&lt;link href=&quot;http://cdn.bootcss.com/bootstrap/3.3.4/css/bootstrap.min.css&quot; rel=&quot;stylesheet&quot;&gt;
        ///	&lt;link href=&quot;http://cdn.bootcss.com/font-aweso [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string weiHtml {
            get {
                return ResourceManager.GetString("weiHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;div class=&quot;col-sm-6 col-md-4 col-lg-3 &quot;&gt;
        ///				&lt;div class=&quot;thumbnail&quot;&gt;
        ///					&lt;a href=&quot;{$二合一链接$}&quot;&gt;
        ///						&lt;img class=&quot;lazy&quot; src=&quot;http://zfcode.com/q/null.png&quot; width=&quot;300&quot; height=&quot;300&quot; data-src=&quot;{$主图$}&quot;
        ///							alt=&quot;Headroom.js&quot;&gt;&lt;/a&gt;
        ///					&lt;div class=&quot;caption&quot;&gt;
        ///						&lt;h4&gt;
        ///							&lt;a href=&quot;{$二合一链接$}&quot;&gt;券后价：{$券后价$}元&lt;/a&gt;
        ///						&lt;/h4&gt;
        ///                        &lt;span &gt;{$文案$}&lt;/span&gt;
        ///						&lt;div class=&quot;kwd&quot; id=&quot;kwd&quot;&gt;
        ///							&lt;span&gt;领券+下单：{$二合一链接$}&lt;/span&gt;&lt;br/&gt;
        ///							&lt;span style=&quot;font-size:10px&quot;&gt;点击图片或者直接复制虚线框内所有内容，打开手机 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string weiHtmlContent {
            get {
                return ResourceManager.GetString("weiHtmlContent", resourceCulture);
            }
        }
    }
}
